# Load data

In [66]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
import numpy as np
import warnings

warnings.filterwarnings('ignore')

%matplotlib inline
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.figsize'] = (10, 6)

# Master
df_pduct = pd.read_parquet('../dataset/cleaned/products.parquet')
df_cus = pd.read_parquet('../dataset/cleaned/customers.parquet')
df_pmot = pd.read_parquet('../dataset/cleaned/promotions.parquet')
df_geo = pd.read_parquet('../dataset/cleaned/geography.parquet')

# Transaction
df_ord = pd.read_parquet('../dataset/cleaned/orders.parquet')
df_item = pd.read_parquet('../dataset/cleaned/order_items.parquet')
df_ship = pd.read_parquet('../dataset/cleaned/shipments.parquet')
df_ret = pd.read_parquet('../dataset/cleaned/returns.parquet')
df_rev = pd.read_parquet('../dataset/cleaned/reviews.parquet')

# Analytical
df_sale = pd.read_parquet('../dataset/cleaned/sales.parquet')
#df_submit = pd.read_parquet('../dataset/sample_submission.csv')

# Operational
df_inv = pd.read_parquet('../dataset/cleaned/inventory.parquet')
df_web = pd.read_parquet('../dataset/cleaned/web_traffic.parquet')

df_pduct.info()
df_cus.info()
df_pmot.info()
df_geo.info()
df_ord.info()
df_item.info()
df_ship.info()
df_ret.info()
df_rev.info()
df_sale.info()
df_inv.info()
df_web.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2412 entries, 0 to 2411
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2412 non-null   string
 1   product_name  2412 non-null   string
 2   category      2412 non-null   category
 3   segment       2412 non-null   category
 4   size          2412 non-null   category
 5   color         2412 non-null   category
 6   price         2412 non-null   float64
 7   cogs          2412 non-null   float64
dtypes: category(4), float64(2), string(2)
memory usage: 86.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121930 entries, 0 to 121929
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          121930 non-null  string
 1   zip                  121930 non-null  string
 2   city                 121930 non-null  category
 3   signup_date          121930 non-null  datetime64[ns]
 4   gender               121930 non-null  category
 5   age_group            121930 non-null  category
 6   acquisition_channel  121930 non-null  category
dtypes: category(4), datetime64[ns](1), string(2)
memory usage: 3.3 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   promo_id             50 non-null     string
 1   promo_name           50 non-null     string
 2   promo_type           50 non-null     category
 3   discount_value       50 non-null     float64
 4   start_date           50 non-null     datetime64[ns]
 5   end_date             50 non-null     datetime64[ns]
 6   applicable_category  50 non-null     category
 7   promo_channel        50 non-null     category
 8   stackable_flag       50 non-null     bool
 9   min_order_value      50 non-null     int64
dtypes: bool(1), category(3), datetime64[ns](2), float64(1), int64(1), string(2)
memory usage: 3.1 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39948 entries, 0 to 39947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip       39948 non-null  string
 1   city      39948 non-null  category
 2   region    39948 non-null  category
 3   district  39948 non-null  category
dtypes: category(3), string(1)
memory usage: 432.1 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646945 entries, 0 to 646944
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        646945 non-null  string
 1   order_date      646945 non-null  datetime64[ns]
 2   customer_id     646945 non-null  string
 3   zip             646945 non-null  string
 4   order_status    646945 non-null  category
 5   payment_method  646945 non-null  category
 6   device_type     646945 non-null  category
 7   order_source    646945 non-null  category
 8   payment_value   646945 non-null  float64
 9   installments    646945 non-null  category
dtypes: category(5), datetime64[ns](1), float64(1), string(3)
memory usage: 27.8 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714669 entries, 0 to 714668
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         714669 non-null  string
 1   product_id       714669 non-null  string
 2   quantity         714669 non-null  int64
 3   unit_price       714669 non-null  float64
 4   discount_amount  714669 non-null  float64
 5   promo_id         714669 non-null  string
 6   promo_id_2       714669 non-null  string
dtypes: float64(2), int64(1), string(4)
memory usage: 38.2 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566067 entries, 0 to 566066
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       566067 non-null  string
 1   ship_date      566067 non-null  datetime64[ns]
 2   delivery_date  566067 non-null  datetime64[ns]
 3   shipping_fee   566067 non-null  float64
dtypes: datetime64[ns](2), float64(1), string(1)
memory usage: 17.3 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39939 entries, 0 to 39938
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   return_id        39939 non-null  string
 1   order_id         39939 non-null  string
 2   product_id       39939 non-null  string
 3   return_date      39939 non-null  datetime64[ns]
 4   return_reason    39939 non-null  category
 5   return_quantity  39939 non-null  int64
 6   refund_amount    39939 non-null  float64
dtypes: category(1), datetime64[ns](1), float64(1), int64(1), string(3)
memory usage: 1.9 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113551 entries, 0 to 113550
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   review_id     113551 non-null  string
 1   order_id      113551 non-null  string
 2   product_id    113551 non-null  string
 3   customer_id   113551 non-null  string
 4   review_date   113551 non-null  datetime64[ns]
 5   rating        113551 non-null  category
 6   review_title  113551 non-null  category
dtypes: category(2), datetime64[ns](1), string(4)
memory usage: 4.5 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3833 entries, 0 to 3832
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     3833 non-null   datetime64[ns]
 1   Revenue  3833 non-null   float64
 2   COGS     3833 non-null   float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 90.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60247 entries, 0 to 60246
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   snapshot_date      60247 non-null  datetime64[ns]
 1   product_id         60247 non-null  string
 2   stock_on_hand      60247 non-null  int64
 3   units_received     60247 non-null  int64
 4   units_sold         60247 non-null  int64
 5   stockout_days      60247 non-null  int64
 6   days_of_supply     60247 non-null  float64
 7   fill_rate          60247 non-null  float64
 8   stockout_flag      60247 non-null  bool
 9   overstock_flag     60247 non-null  bool
 10  reorder_flag       60247 non-null  bool
 11  sell_through_rate  60247 non-null  float64
 12  product_name       60247 non-null  string
 13  category           60247 non-null  category
 14  segment            60247 non-null  category
 15  year               60247 non-null  int64
 16  month              60247 non-null  int64
dtypes: bool(3), category(2), datetime64[ns](1), float64(3), int64(6), string(2)
memory usage: 5.8 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3652 entries, 0 to 3651
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      3652 non-null   datetime64[ns]
 1   sessions                  3652 non-null   int64
 2   unique_visitors           3652 non-null   int64
 3   page_views                3652 non-null   int64
 4   bounce_rate               3652 non-null   float64
 5   avg_session_duration_sec  3652 non-null   float64
 6   traffic_source            3652 non-null   category
dtypes: category(1), datetime64[ns](1), float64(2), int64(3)
memory usage: 175.1 KB

# gen file test

In [67]:
df_sale_train = df_sale[['Date', 'COGS']].copy()
df_sale_test = df_sale[['Date', 'COGS']].copy()

split_day = '2022-12-31'
df_sale_train = df_sale_train[(df_sale_train['Date'] <= split_day) & (df_sale_train['Date'] >= '2013-01-01')]
df_sale_test = df_sale_test[(df_sale_test['Date'] > split_day) & (df_sale_train['Date'] >= '2013-01-01')]

df_sale_train = df_sale_train.sort_values(by='Date')

In [68]:
df_sale_train['day'] = df_sale_train['Date'].dt.day
df_sale_train['month'] = df_sale_train['Date'].dt.month
df_sale_train['year'] = df_sale_train['Date'].dt.year
df_sale_train['month_day'] = df_sale_train['Date'].dt.strftime('%m-%d')

In [69]:
df_sale_train['is_Spring_promotion'] = df_sale_train['month_day'].between('03-18', '04-17')
df_sale_train['is_MidYear_promotion'] = df_sale_train['month_day'].between('06-23', '07-22')
df_sale_train['is_FallLauch_promotion'] = df_sale_train['is_Special_Fall_promotion'] = df_sale_train['month_day'].between('08-30', '10-01') | ((df_sale_train['year'] % 4 == 1) & (df_sale_train['month_day'] == '10-02'))
df_sale_train['is_YearEnd_promotion'] = df_sale_train['month_day'].between('11-18', '12-31') |  df_sale_train['month_day'].between('01-01', '01-02') # có nhiều ngày kết thúc khác nhưng fix vào 02/01 hàng năm
df_sale_train['is_Rural_promotion'] = (df_sale_train['year'] % 2 == 1)  & df_sale_train['month_day'].between('01-30', '03-01') # từ năm 2015 mới cố định ngày kết thúc
df_sale_train['is_Urban_promotion'] = (df_sale_train['year'] % 2 == 1)  & df_sale_train['month_day'].between('07-30', '09-02')

In [70]:
df_sale_train['category_promotion'] = -1 # default: if it isn't in any promotion

#decode category_promotion: 0 -> All ; 1 -> Outdoor ; 2 -> Steetwear
df_sale_train.loc[(df_sale_train['is_Spring_promotion'] | df_sale_train['is_MidYear_promotion'] | df_sale_train['is_YearEnd_promotion']), 'category_promotion'] = 0
df_sale_train.loc[df_sale_train['is_Rural_promotion'], 'category_promotion'] = 1
df_sale_train.loc[df_sale_train['is_Urban_promotion'], 'category_promotion'] = 2

In [71]:
df_sale_train.to_parquet('sale_train_vi.parquet')

# Order status

In [72]:
df_check = df_ord[['order_id', 'order_date', 'order_status', 'payment_method']].copy()
df_check = df_check.merge(df_ship, on='order_id', how='left')

df_check['is_returned'] = df_check['order_id'].isin(df_ret['order_id']).astype(bool)
df_check['is_reviewed'] = df_check['order_id'].isin(df_rev['order_id']).astype(bool)

# df_check.info()
# print(df_check['order_status'].value_counts())

statuses = df_check['order_status'].unique()

for status in statuses:
    print("-" * 50)
    df_temp = df_check[df_check['order_status'] == status]
    total_rows = len(df_temp)
    
    count_return = len(df_temp[df_temp['is_returned'] == 1])
    count_ship = df_temp['ship_date'].notna().sum()
    
    print(f"--- order_status: {status.upper()} ---")
    print(f"Tổng số đơn: {total_rows}")
    print(f"Số đơn có tồn tại dữ liệu shipments: {count_ship}")
    print(f"Số đơn có tồn tại dữ liệu return: {count_return}")

--------------------------------------------------
--- order_status: DELIVERED ---
Tổng số đơn: 516716
Số đơn có tồn tại dữ liệu shipments: 516192
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: RETURNED ---
Tổng số đơn: 36142
Số đơn có tồn tại dữ liệu shipments: 36113
Số đơn có tồn tại dữ liệu return: 36062
--------------------------------------------------
--- order_status: SHIPPED ---
Tổng số đơn: 13773
Số đơn có tồn tại dữ liệu shipments: 13762
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: CANCELLED ---
Tổng số đơn: 59462
Số đơn có tồn tại dữ liệu shipments: 0
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: PAID ---
Tổng số đơn: 13577
Số đơn có tồn tại dữ liệu shipments: 0
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: CREATED ---
Tổng số đơn: 7275
Số đơn có tồn tại dữ liệu shipments: 0
Số đơn có tồn tại dữ liệu return: 0

# Inventory

In [73]:
df_inv.describe(include='all')
df_check = df_inv.sort_values(by='snapshot_date')
df_check['recei_sold'] = df_check['units_received'] - df_check['units_sold']
df_check = df_check[['snapshot_date', 'product_id', 'stock_on_hand', 'units_received', 'units_sold', 'stockout_days', 'days_of_supply', 'overstock_flag']]

df_temp = df_check[df_check['product_id'] == 1202]
display(df_temp.head(10))

df_temp = df_check[df_check['product_id'] == 1942]
display(df_temp.head(10))

Empty DataFrame
Columns: [snapshot_date, product_id, stock_on_hand, units_received, units_sold, stockout_days, days_of_supply, overstock_flag]
Index: []

Empty DataFrame
Columns: [snapshot_date, product_id, stock_on_hand, units_received, units_sold, stockout_days, days_of_supply, overstock_flag]
Index: []