# Load data

In [70]:
import pandas as pd

print("Loading data...")

# Master
df_pduct = pd.read_csv('../dataset/products.csv', low_memory=False)
df_cus = pd.read_csv('../dataset/customers.csv', low_memory=False)
df_pmot = pd.read_csv('../dataset/promotions.csv', low_memory=False)
df_geo = pd.read_csv('../dataset/geography.csv', low_memory=False)

# Transaction
df_ord = pd.read_csv('../dataset/orders.csv', low_memory=False)
df_item = pd.read_csv('../dataset/order_items.csv', low_memory=False)
df_pay = pd.read_csv('../dataset/payments.csv', low_memory=False)
df_ship = pd.read_csv('../dataset/shipments.csv', low_memory=False)
df_ret = pd.read_csv('../dataset/returns.csv', low_memory=False)
df_rev = pd.read_csv('../dataset/reviews.csv', low_memory=False)

# Analytical
df_sale = pd.read_csv('../dataset/sales.csv', low_memory=False)
#df_submit = pd.read_csv('../dataset/sample_submission.csv', low_memory=False)

# Operational
df_inv = pd.read_csv('../dataset/inventory.csv', low_memory=False)
df_web = pd.read_csv('../dataset/web_traffic.csv', low_memory=False)

print("Load data successfully")

Loading data...
Load data successfully

# Order status

In [71]:
df_check = df_ord[['order_id', 'order_date', 'order_status', 'payment_method']].copy()
df_check = df_check.merge(df_ship, on='order_id', how='left')

df_check['is_returned'] = df_check['order_id'].isin(df_ret['order_id']).astype(bool)
df_check['is_reviewed'] = df_check['order_id'].isin(df_rev['order_id']).astype(bool)

# df_check.info()
# print(df_check['order_status'].value_counts())

statuses = df_check['order_status'].unique()

for status in statuses:
    print("-" * 50)
    df_temp = df_check[df_check['order_status'] == status]
    total_rows = len(df_temp)
    
    count_return = len(df_temp[df_temp['is_returned'] == 1])
    count_ship = df_temp['ship_date'].notna().sum()
    
    print(f"--- order_status: {status.upper()} ---")
    print(f"Tổng số đơn: {total_rows}")
    print(f"Số đơn có tồn tại dữ liệu shipments: {count_ship}")
    print(f"Số đơn có tồn tại dữ liệu return: {count_return}")

--------------------------------------------------
--- order_status: DELIVERED ---
Tổng số đơn: 516716
Số đơn có tồn tại dữ liệu shipments: 516192
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: RETURNED ---
Tổng số đơn: 36142
Số đơn có tồn tại dữ liệu shipments: 36113
Số đơn có tồn tại dữ liệu return: 36062
--------------------------------------------------
--- order_status: SHIPPED ---
Tổng số đơn: 13773
Số đơn có tồn tại dữ liệu shipments: 13762
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: CANCELLED ---
Tổng số đơn: 59462
Số đơn có tồn tại dữ liệu shipments: 0
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: PAID ---
Tổng số đơn: 13577
Số đơn có tồn tại dữ liệu shipments: 0
Số đơn có tồn tại dữ liệu return: 0
--------------------------------------------------
--- order_status: CREATED ---
Tổng số đơn: 7275
Số đơn có tồn tại dữ liệu shipments: 0
Số đơn có tồn tại dữ liệu return: 0

# Inventory

In [72]:
df_inv.describe(include='all')
df_check = df_inv.sort_values(by='snapshot_date')
df_check['recei_sold'] = df_check['units_received'] - df_check['units_sold']
df_check = df_check[['snapshot_date', 'product_id', 'stock_on_hand', 'units_received', 'units_sold', 'stockout_days', 'days_of_supply', 'overstock_flag']]

df_temp = df_check[df_check['product_id'] == 1202]
display(df_temp.head(10))

df_temp = df_check[df_check['product_id'] == 1942]
display(df_temp.head(10))

,snapshot_date,product_id,stock_on_hand,units_received,units_sold,stockout_days,days_of_supply,overstock_flag
29523,2012-07-31,1202,32,12,10,0,96.0,1
29524,2012-08-31,1202,33,8,7,2,141.4,1
29525,2012-09-30,1202,33,1,1,0,990.0,1
29526,2012-10-31,1202,33,1,1,2,990.0,1
29527,2012-12-31,1202,33,1,1,2,990.0,1
29528,2013-01-31,1202,33,1,1,0,990.0,1
29529,2013-02-28,1202,33,3,3,1,330.0,1
29530,2013-03-31,1202,33,4,4,2,247.5,1
29531,2013-04-30,1202,34,11,10,2,102.0,1
29532,2013-05-31,1202,36,11,9,2,120.0,1

,snapshot_date,product_id,stock_on_hand,units_received,units_sold,stockout_days,days_of_supply,overstock_flag
45113,2012-07-31,1942,35,13,11,0,95.5,1
45114,2012-08-31,1942,38,18,15,1,76.0,0
45115,2012-09-30,1942,40,12,10,2,120.0,1
45116,2012-10-31,1942,41,8,7,2,175.7,1
45117,2012-11-30,1942,42,8,7,2,180.0,1
45118,2012-12-31,1942,44,23,21,2,62.9,0
45119,2013-01-31,1942,44,7,7,2,188.6,1
45120,2013-02-28,1942,45,14,13,1,103.8,1
45121,2013-03-31,1942,46,9,8,1,172.5,1
45122,2013-04-30,1942,51,28,23,1,66.5,0